### ISSUE TITLE
应该说你这个要怎么使用呢

### ISSUE THREAD

**Issue by zengcanxiang** [hqzxzwb/ProguardDictionaryGenerator#1]
谢谢解答

**Comment by hqzxzwb** [comment]
如README所写，“通过配置-obfuscationdictionary,-classobfuscationdictionary和-packageobfuscationdictionary分别指定变量/方法名、类名、包名混淆后的字符串集”。

**Comment by zengcanxiang** [comment]
恩，就是这个配置。相当于你实现了一个字符串集给我们使用，这个需要分别指定，那么你这个字符串集指定有什么要求么？全部指定一个字符串集么？

**Comment by hqzxzwb** [comment]
这是proguard提供的三个参数，分别用来提供不同方面的命名字典。

参考https://www.guardsquare.com/en/proguard/manual/usage#obfuscationoptions

不过这里也提到了，指定字典的意义并不特别大。通过再次混淆jar包就可以轻易地将这些名称变回abcd这样的值。

在我看来为它们配置同一个字符串集就可以了，没有必要去为他们配置不同的字典。但是理论上讲，你确实可以自由选择，包括不配置有的参数。
